### ISSUE TITLE
build.prop editing disabled

### ISSUE THREAD

**Issue by darren3** [Magisk-Modules-Repo/MagiskHidePropsConf#10]
Hello, my propsconf.log shows build.prop editing disabled but I can't figure out why. No conflicting modules are listed. I have tried disabling modules but this has made no difference. I am using a project treble GSI rom, running Android 8.1.

**Comment by darren3** [comment]
And my propslogs.

[propslogs.tar.gz](https://github.com/Magisk-Modules-Repo/MagiskHide-Props-Config/files/2386484/propslogs.tar.gz)

**Comment by Didgeridoohan** [comment]
Yup. Somethingis is definitely wrong. Must be something with the logic in checking for the stock prop values.

Will take a look when I get an opportunity.

**Comment by darren3** [comment]
Great, thanks.

**Comment by Didgeridoohan** [comment]
So... I finally had some peace and quiet to sit down and look at this. Started looking through the code but couldn't find anything. Hm.... I went back to this issue and realised I was a bit sloppy reading the bug description the first time around.

The log is supposed to say that build.prop editing is disabled if you haven't actually enabled it.

@darren3 Did you even run the props script and enable "Improved hiding"? Because if you didn't, there's no bug... 😆 Everything in your logs and settings look exactly as they should.

**Comment by darren3** [comment]
Hi, I hadn't enabled Improved hiding. Thanks for having a look.
