### ISSUE TITLE
Boot scripts don't run on Mi 10T Pro

### ISSUE THREAD

**Issue by HaleTom** [Magisk-Modules-Repo/MagiskHidePropsConf#106]
I've tried all 3 options for boot stage to load the boot script, and also tried enabling background.

Sadly: no cigar.

Please find the logs [here](https://drive.google.com/file/d/1fyqDguyqfbPyoa3-2XTaFlQvI4z90Grb/view?usp=sharing), and let me know if there's anything else I can try.

Thanks for all your great work on this!

**Comment by Didgeridoohan** [comment]
With your current setup the service.sh script doesn't finish, but the previous boot had it working fine (according to the logs at least).

But, looking at your Magisk log there are plenty of busybox errors, so you've got something wrong there... That's probably the source of your problems.

The error is:
`execve /dev/WVGZnV/.magisk/busybox/busybox failed with 8: Exec format error`

I think I've seen something similar mentioned elsewhere, but I'm going to have to look around a bit because I can't remember at the moment.

**Comment by Didgeridoohan** [comment]
This is a Magisk problem. Your installation is broken and there's something wrong with the busybox binary (or something like that). You'll need to figure that out first... Maybe a uninstall and reinstall of Magisk would do it.

**Comment by Didgeridoohan** [comment]
@HaleTom Better late than never I figured out where I'd seen that issue before...

If a tell reinstall of Magisk didn't work you could try this (if this is still an issue):
https://forum.xda-developers.com/t/module-magiskhide-props-config-safetynet-prop-edits-and-more-v6-0-1.3789228/post-85057131

**Comment by HaleTom** [comment]
Ooh, thanks so much for posting this.  It loads just fine now :)
