### ISSUE TITLE
Fingerprint for Xiaomi Mi 11 Pro - Chinese 

### ISSUE THREAD

**Issue by Hot12345** [Magisk-Modules-Repo/MagiskHidePropsConf#120]
Hi,

Im having a Xiaomi 11 Pro - Chinese.
Flashed to a Global official ROM of Xiaomi, but now having problem to pass Safetynet.

I want to apply the fingerprint of this device, but there is no fingerprint available... How to apply a custom one that works to pass SafetyNet? I want really to pass Safetynet on this device.

**Comment by Didgeridoohan** [comment]
If you're using the stock ROM I would expect that you do not need to use this module to apply a certified print. Stock ROMs usually assist already have a certified print... Although, Xiaomi are weird so I wouldn't be surprised by anything they do by now. You can of course test by using one of the prints on the list, even if it [doesn't exactly match your setup/device](https://github.com/Magisk-Modules-Repo/MagiskHide-Props-Config/blob/master/README.md#can-i-use-any-fingerprint).

Check the module docs for plenty of info on how to apply a print that's not included in the module list (for example with a [custom prints list](https://github.com/Magisk-Modules-Repo/MagiskHide-Props-Config/blob/master/README.md#custom-fingerprints-list)). You'll also find info on how to [submit](https://github.com/Magisk-Modules-Repo/MagiskHide-Props-Config/blob/master/README.md#how-do-i-submit-a-fingerprint) a print for inclusion in the module list. Another important section of the docs would be the issues section on passing [CTS](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/blob/master/README.md#i-still-cant-pass-the-ctsprofile-check).

Closing this since it's not an issue with the module and everything you're mentioning should already be covered by the docs.
