### ISSUE TITLE
Android 12 : props inaccessible or not found

### ISSUE THREAD

**Issue by 57382** [Magisk-Modules-Repo/MagiskHidePropsConf#127]
/system/bin/sh: props: inaccessible or not found

in Android 11 works fine.

**Comment by Retrodynen** [comment]
same here.

**Comment by ZachBacon** [comment]
Android 13 as well

**Comment by selukov** [comment]
hi I try change CTS profile but:
/system/bin/sh: props: inaccessible or not found

magiskhidepropsconf 6.1.2 installed see picture
please tell me what to do?

Android 13 : props inaccessible or not found 
[![Screenshot-20230207-003629-Termux.jpg](https://i.postimg.cc/FK6p0p8s/Screenshot-20230207-003629-Termux.jpg)](https://postimg.cc/yJF0Hm7w)
[![Screenshot-20230207-001542-Magisk.jpg](https://i.postimg.cc/zXMfZRsH/Screenshot-20230207-001542-Magisk.jpg)](https://postimg.cc/HVwmbjsT)

**Comment by esauvc** [comment]
For everybody with this problem I'm going to give the solution. The problem is that the terminal cannot find this module installed in Magisk because you have hide Magisk with another name so with this process of hiding you cannot use it but you only need to go to Magisk to settings and choose not to hide the app (reverse process) and you will have again Magisk as it was at the beginning and you can do again the process: su and after props and yes! you can use it. Have a good day!

**Comment by ghhxdd** [comment]
Just type 
su
props
In termux , me working
