### ISSUE TITLE
Hangs in boot screen

### ISSUE THREAD

**Issue by darkdragon-001** [Magisk-Modules-Repo/MagiskHidePropsConf#38]
While this module installes perfectly for me (Magisk 20, Android 9 [RR 7], Galaxy S6), the device doesn't boot any more when fingerprint is modified.

_(When the module is deactivated, it boots again but SafetyNet does not pass of course)_

**Comment by Didgeridoohan** [comment]
I would need to see the logs showing this to be able to help. See the docs for that logs are useful and where to find them.

**Comment by darkdragon-001** [comment]
Find `logcat` logs [here](https://forum.xda-developers.com/showpost.php?p=80534747&postcount=213).

**Comment by Didgeridoohan** [comment]
Sounds like there's something about the RR 7.0.2 release, rather than the module. You could run a couple tests to try to narrow down the issue.

Try changing the fingerprint boot stage to both post-fd-data and late_start service, to see if it makes any difference. You'll find that setting under the "Edit device fingerprint" menu. And if that makes no difference you can try doing the same for the security patch date (same menu).

Next thing to try is to edit the device fingerprint without the module. Put this in a file in first /data/adb/post-fs-data.d and then /data/adb/service.d to see if either of those work or not (don't forget to give the file execution permission):
```
#!/system/bin/sh

ro.build.fingerprint=samsung/zerofltexx/zeroflte:7.0/NRD90M/G920FXXS5EQL1:user/release-keys
ro.bootimage.build.fingerprint=samsung/zerofltexx/zeroflte:7.0/NRD90M/G920FXXS5EQL1:user/release-keys
ro.vendor.build.fingerprint=samsung/zerofltexx/zeroflte:7.0/NRD90M/G920FXXS5EQL1:user/release-keys
ro.build.description=zerofltexx-user 7.0 NRD90M G920FXXS5EQL1 release-keys
```

If that still doesn't work, start deleting one prop after another from the file and see if that helps. Start from the bottom with ro.build.description, reboot, then ro.vendor.build.fingerprint, reboot, and so on. That way we can rule out of it's a specific prop causing issues or not.

I'm seeing this error in the log for the failed boot (but not the other two) and I'm suspecting it has something to do with it:
```Cannot determine initial API level of the device```

If that's the issue there's nothing I can do about it, but something for the ROM developer. First give the above tests a try though and we might be able to figure something out

**Comment by Didgeridoohan** [comment]
Probably a ROM issue. Closing.
