### ISSUE TITLE
No Busybox found

### ISSUE THREAD

**Issue by cwtechshiz** [Magisk-Modules-Repo/MagiskHidePropsConf#53]
installed osm0sis's busybox from magisk and still getting error that its not found.. currently running magisk 20.4 on oxygenos 10.3.2 (oneplus6t) if that helps. i did verify busybox is installed and working, if you can point me towards how your module checks for it ill be glad to debug

**Comment by Didgeridoohan** [comment]
Module logs might help:
https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/blob/master/README.md#logs

If you want to troubleshoot on your own, this is where you'll find the specific code:
https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/blob/9a6833cbb1bc909e572e3b452bed0ece7718d4ac/common/util_functions.sh#L296

As you can see, if you do have the Busybox NDK module installed, the scripts should find it. And failing that there should be no issues with any other properly installed Busybox since the fallback is to use the which busybox command to find it.

**Comment by cwtechshiz** [comment]
so yeah i figured that out before seeing your reply and sorry for not digging through all 200+ pages on the support thread. i believe it is failing because no matter how i go about installing busybox it will not run as root in a terminal. the busybox command only runs as a non-root user oddly. osm0sis's module in magisk constantly says update in the downloads like it isnt installing correctly but i get no errors saying so. also tried flashing busybox in twrp instead and got the same result. however using the questionable busybox installer found on playstore actually let me run it as root but still no bosybox found message when running props, also busybox did not stick after reboot. 

Not having much luck finding any help searching your online about similar issues

would you like all of these files in the log folder? is it going to show data from every time ive failed to launch?

**Comment by Didgeridoohan** [comment]
Before you do anything else, check in /data/adb if there is a magisk.img file. If you find that, delete it and try again.

There's been a couple of similar instances of your issue discussed in support thread lately and from what we managed to work out it seemed like they couldn't install Busybox from the Magisk downloads because it found this file from a previous Magisk installation (there was a bug in the Magisk cleanup code) and unsuccessfully tried to use it.

If you can't get things working I would need all those files together with the Magisk log. The install log from the Busybox module would also be useful.

**Comment by cwtechshiz** [comment]
that worked. im not sure if the theory of a previous install is correct though because i just completely wiped everything and started fresh with the latest version of magisk. thank you for the quick response

**Comment by Didgeridoohan** [comment]
So you did have a Magisk image in /data/adb? If so it is a remnant from an old installation, since that was removed in Magisk v19.0. Did you wipe /data?

I'll close this, since the main issue has been fixed.
