### ISSUE TITLE
can't find my android version

### ISSUE THREAD

**Issue by bemyfrnd** [Magisk-Modules-Repo/MagiskHidePropsConf#94]
I am using lineage os 17.1 with magisk 22 with micro g.
I can't bypass safetynet .
When I go to fingerprint menu, select my device (xiaomi redmi note 5 pro) I only see option for android version 8 and 9, but my android is 10.

**Comment by Didgeridoohan** [comment]
That's because no-one has submitted an Android 10 fingerprint for that device. If you want, you could help by providing one:
https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/blob/master/README.md#how-do-i-submit-a-fingerprint

To pass CTS you usually don't have to match the Android version though...

But, microG can't pass CTS anyway so for you it doesn't really matter.

**Comment by bemyfrnd** [comment]
What do you mean? If I am using microg, I cannot pass safetynet?!

**Comment by Didgeridoohan** [comment]
Exactly.

**Comment by bemyfrnd** [comment]
This is a very bad news...There are no workaround or tricks?!

**Comment by Didgeridoohan** [comment]
Not that I know of, or have heard of. But I don't use microG, so you're probably better off doing your own research on this...
